<a href="https://colab.research.google.com/github/L65FREAD/ScarewareDetection/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploded =files.upload()

Saving scarewaredataset.csv to scarewaredataset.csv


In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
import io

In [4]:
from os import name
FileName=list(uploded.keys())[0]
data =pd.read_csv(io.BytesIO(uploded[FileName]))

for name in data.columns:
  data[name]= data[name].astype(str)

le=LabelEncoder()

for features in data.columns:
  if data[features].dtype == object:
    data[features]=le.fit_transform(data[features])

y=data.pop(' Label')
X=data

X_Train, X_Test, y_Train, y_Test= train_test_split(X, y, test_size=0.2, random_state=45)

nb = GaussianNB()
nb.fit(X_Train, y_Train)

GaussianNB()

In [6]:
y_pred= nb.predict(X_Test)

print("Accuracy:", metrics.accuracy_score(y_Test, y_pred))
print("Confusion Matrix: \n", metrics.confusion_matrix(y_Test, y_pred))

Accuracy: 0.5859748300693183
Confusion Matrix: 
 [[6527   13  326   75   39    1   22    7   17   37  339   60]
 [  20  114    0   80   25   22    3   10    0    0    3  382]
 [ 165    2  517    6    6    0    0    0    0    5   51    4]
 [  75   45    8  287   42    1    1    1    0    1   18  222]
 [  48   57    2  220   47    7    2    3    0    0    7  263]
 [   2   11    0    0    1   99   17  114   88    0    9  339]
 [   3   18    0   44   12   14   38  224  163    1   26  153]
 [   3    7    0    0    0   36   25  248  173    2   14  168]
 [   0    3    0    0    0   22   28  196  247    0   26  128]
 [ 141    1    0    0    0    0   89   77  153  102   86    1]
 [  61    0    0    0    0    0  203   62  137  142  110    0]
 [  12   37    0   34    7   57    3   32    0    0    4  371]]


In [7]:
accuracy= "Accuracy:", str(metrics.accuracy_score(y_Test, y_pred))
confusionMatrix = "Confusion Matrix: \n", str(metrics.confusion_matrix(y_Test, y_pred))
lines = [accuracy, confusionMatrix]
with open('naivebayesresults.txt', 'w') as f:
    f.writelines(str(lines))
files.download('naivebayesresults.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>